Add missing migration
eduNEXT/eox-audit-model pull request #4
Opened 2020-12-22 22:22 UTC by magajh

This PR adds the missing migration from the changes made when adding support for juniper.

2020-12-23 21:47 UTC, andrey-canon approved these changes

2020-12-28 13:55 UTC, andrey-canon requested changes

2020-12-28 13:55 UTC, andrey-canon commented on eox_audit_model/tests/tests_models.py
> +            domain=domain
trailing comma

2020-12-28 13:55 UTC, andrey-canon commented on eox_audit_model/tests/tests_models.py
> +            domain='Missing domain.'
trailing comma

2020-12-28 15:23 UTC, magajh commented on eox_audit_model/tests/tests_models.py
> +            domain=domain
Done

2020-12-28 15:51 UTC, magajh commented on eox_audit_model/tests/tests_models.py
> +            domain='Missing domain.'
Done

2020-12-28 16:54 UTC, andrey-canon approved these changes

2020-12-28 18:44 UTC, merged